version: '3.8'
services:
  app:
    image: php:8.2-fpm
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: casivar
      POSTGRES_USER: casivar
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  db_data:
